# UwU vs. OwO binary classification attempt - Curie

SPDX-License-Identifier: 0BSD

This uses text-similarity-curie-001, a first-generation OpenAI embedding model.
The terms are only narrowly distinguished.

In [1]:
import numpy as np
import openai
import openai.embeddings_utils

In [2]:
openai.api_key_path = '.api_key'

In [3]:
def embed_one(text):
    embedding = openai.embeddings_utils.get_embedding(
        text=text,
        engine='text-similarity-curie-001',
    )
    return np.array(embedding)

In [4]:
def embed_many(texts):
    embeddings = openai.embeddings_utils.get_embeddings(
        list_of_text=texts,
        engine='text-similarity-curie-001',
    )
    return np.array(embeddings)

In [5]:
uwu_owo = embed_many(['UwU', 'OwO'])

In [6]:
uwu_owo @ embed_one('relaxation')

array([0.68027522, 0.68990227])

In [7]:
uwu_owo @ embed_one('surprise')

array([0.73244287, 0.75508899])

In [8]:
uwu_owo @ embed_one('excitement')

array([0.67284418, 0.72396868])